# Change the following to your desired values:
#   __ACCOUNT_NUMBER__
#   __ECR_REGION__
#   __ECR_REPOSITORY_NAME__
#   __ECS_CONTAINER_NAME__ 

version: 0.2
phases:
  install:
    runtime-versions:
      docker: 18
      python: 3.7
      ruby: 2.6
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version      
      - aws ecr get-login-password --region ap-southeast-1
      - REPOSITORY_URI=234507186020.dkr.ecr.ap-southeast-1.amazonaws.com/pegepay
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=build-$(echo $CODEBUILD_BUILD_ID | awk -F":" '{print $2}')
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t 234507186020.dkr.ecr.ap-southeast-1.amazonaws.com/pegepay:latest.
      - docker tag 234507186020.dkr.ecr.ap-southeast-1.amazonaws.com/pegepay:latest 234507186020.dkr.ecr.ap-southeast-1.amazonaws.com/pegepay:v1
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push 234507186020.dkr.ecr.ap-southeast-1.amazonaws.com/pegepay:latest
      - docker push 234507186020.dkr.ecr.ap-southeast-1.amazonaws.com/pegepay:v1
artifacts:
  files:
    - imageDetail.json
